### ISSUE TITLE
Evolve into fsspec protocol

### ISSUE THREAD

**Issue by astrojuanlu** [astrojuanlu/kedro-kaggle-dataset#2]
After discussing with the Kedro TSC, we considered an alternative to this implementation that doesn't couple the _format_ of the files in the dataset with their _location_ (Kaggle, in this case), which is implementing a custom fsspec backend https://filesystem-spec.readthedocs.io/en/latest/developer.html#implementing-a-backend

```
titanic_kaggle:
  type: ???  # No heterogeneous dataset yet
  path: kaggle://competition/
  credentials: kaggle_credentials
```

and trying to leverage `PartitionedDataSet` https://docs.kedro.org/en/stable/data/kedro_io.html#partitioned-dataset-definition

```yaml
train_csvs:
  type: PartitionedDataSet
  path: data/02_intermediate/train
  dataset: pandas.CSVDataSet
```
